# Data Wrangling - Telecom Churn Prediction

Loading the required libraries

In [1]:
#load python packages
import os
import pandas as pd
import datetime
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline

Reading the current working directory

In [2]:
os.listdir()

['.ipynb_checkpoints',
 '03072020 Data Wrangling - Telecom Churn Prediction.ipynb',
 'dataset.csv']

<font color='teal'> **Load the data into a pandas dataframe and print the first five rows of the dataframe.**</font>

In [3]:
df = pd.read_csv('dataset.csv')
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

### Let's organize the data by creating sub-folders

In [5]:
newfolders = ['data', 'figures', 'models']
for newfolder in newfolders :
    try:
        os.mkdir(newfolder)
    except OSError:
        print ("Creation of the directory %s failed" % newfolder)
    else:
        print ("Successfully created the directory %s " % newfolder)

Successfully created the directory data
Successfully created the directory figures
Successfully created the directory models

In [6]:
os.listdir()

['.ipynb_checkpoints',
 '03072020 Data Wrangling - Telecom Churn Prediction.ipynb',
 'data',
 'dataset.csv',
 'figures',
 'models']

### Now, lets explore the data

In [7]:
df.columns

Index(['customerID', 'gender', 'SeniorCitizen', 'Partner', 'Dependents',
       'tenure', 'PhoneService', 'MultipleLines', 'InternetService',
       'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport',
       'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling',
       'PaymentMethod', 'MonthlyCharges', 'TotalCharges', 'Churn'],
      dtype='object')

In [8]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges         object
Churn                object
dtype: object

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

### Table description
<table align='left'>
<tr><th style="text-align:left">Column Name</th><th style="text-align:left">Column Description</th></tr>
<tr><td style="text-align:left">customerID</td><td style="text-align:left">Customer ID</td></tr>
<tr><td style="text-align:left">gender</td><td style="text-align:left">Whether the customer is a male or a female</td></tr>
<tr><td style="text-align:left">SeniorCitizen</td><td style="text-align:left">Whether the customer is a senior citizen or not (1, 0)</td></tr>
<tr><td style="text-align:left">Partner</td><td style="text-align:left">Whether the customer has a partner or not (Yes, No)</td></tr>
<tr><td style="text-align:left">Dependents</td><td style="text-align:left">Whether the customer has dependents or not (Yes, No)</td></tr>
<tr><td style="text-align:left">tenure</td><td style="text-align:left">Number of months the customer has stayed with the company</td></tr>
<tr><td style="text-align:left">PhoneService</td><td style="text-align:left">Whether the customer has a phone service or not (Yes, No)</td></tr>
<tr><td style="text-align:left">MultipleLines</td><td style="text-align:left">Whether the customer has multiple lines or not (Yes, No, No phone service)</td></tr>
<tr><td style="text-align:left">InternetService</td><td style="text-align:left">Customerâ€™s internet service provider (DSL, Fiber optic, No)</td></tr>
<tr><td style="text-align:left">OnlineSecurity</td><td style="text-align:left">Whether the customer has online security or not (Yes, No, No internet service)</td></tr>
<tr><td style="text-align:left">OnlineBackup</td><td style="text-align:left">Whether the customer has online backup or not (Yes, No, No internet service)</td></tr>
<tr><td style="text-align:left">DeviceProtection</td><td style="text-align:left">Whether the customer has device protection or not (Yes, No, No internet service)</td></tr>
<tr><td style="text-align:left">TechSupport</td><td style="text-align:left">Whether the customer has tech support or not (Yes, No, No internet service)</td></tr>
<tr><td style="text-align:left">StreamingTV</td><td style="text-align:left">Whether the customer has streaming TV or not (Yes, No, No internet service)</td></tr>
<tr><td style="text-align:left">StreamingMovies</td><td style="text-align:left">Whether the customer has streaming movies or not (Yes, No, No internet service)</td></tr>
<tr><td style="text-align:left">Contract</td><td style="text-align:left">The contract term of the customer (Month-to-month, One year, Two year)</td></tr>
<tr><td style="text-align:left">PaperlessBilling</td><td style="text-align:left">Whether the customer has paperless billing or not (Yes, No)</td></tr>
<tr><td style="text-align:left">PaymentMethod</td><td style="text-align:left">The customerâ€™s payment method (Electronic , Mailed , Bank transfer (automatic), Credit card (automatic))</td></tr>
<tr><td style="text-align:left">MonthlyCharges</td><td style="text-align:left">The amount charged to the customer monthly</td></tr>
<tr><td style="text-align:left">TotalCharges</td><td style="text-align:left">The total amount charged to the customer</td></tr>
<tr><td style="text-align:left">Churn</td><td style="text-align:left">Whether the customer churned or not (Yes or No)</td></tr>
</table>

##### Since the total charges column is of object type, lets convert that to numeric

In [10]:
df.TotalCharges = pd.to_numeric(df.TotalCharges, errors='coerce')

In [11]:
df.dtypes

customerID           object
gender               object
SeniorCitizen         int64
Partner              object
Dependents           object
tenure                int64
PhoneService         object
MultipleLines        object
InternetService      object
OnlineSecurity       object
OnlineBackup         object
DeviceProtection     object
TechSupport          object
StreamingTV          object
StreamingMovies      object
Contract             object
PaperlessBilling     object
PaymentMethod        object
MonthlyCharges      float64
TotalCharges        float64
Churn                object
dtype: object

In [12]:
df.isnull().sum()

customerID           0
gender               0
SeniorCitizen        0
Partner              0
Dependents           0
tenure               0
PhoneService         0
MultipleLines        0
InternetService      0
OnlineSecurity       0
OnlineBackup         0
DeviceProtection     0
TechSupport          0
StreamingTV          0
StreamingMovies      0
Contract             0
PaperlessBilling     0
PaymentMethod        0
MonthlyCharges       0
TotalCharges        11
Churn                0
dtype: int64

As we can observe here that post converting the <code>ToatlCharges</code> to numeric, there are 11 null values in that column. Let's see the relationship between <code>MonthlyCharges</code> and <code>TotalCharges</code> so that we can impute it.

In [16]:
df[df['TotalCharges']==df['MonthlyCharges']*df['tenure']]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
20,8779-QRDMV,Male,1,No,No,1,No,No phone service,DSL,No,...,Yes,No,No,Yes,Month-to-month,Yes,Electronic check,39.65,39.65,Yes
22,1066-JKSGK,Male,0,No,No,1,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Mailed check,20.15,20.15,Yes
27,8665-UTDHZ,Male,0,Yes,Yes,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,No,Electronic check,30.20,30.20,Yes
33,7310-EGVHZ,Male,0,No,No,1,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Month-to-month,No,Bank transfer (automatic),20.20,20.20,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6979,5351-QESIO,Male,0,No,Yes,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,No,Mailed check,24.20,24.20,No
7010,0723-DRCLG,Female,1,Yes,No,1,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,74.45,74.45,Yes
7016,1471-GIQKQ,Female,0,No,No,1,Yes,No,DSL,No,...,No,No,No,No,Month-to-month,No,Electronic check,49.95,49.95,No
7018,1122-JWTJW,Male,0,Yes,Yes,1,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,70.65,70.65,Yes
7032,6894-LFHLY,Male,1,No,No,1,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,75.75,75.75,Yes

In [21]:
df[df['TotalCharges'].isnull()]

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
488,4472-LVYGI,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,Yes,Bank transfer (automatic),52.55,NaN,No
753,3115-CZMZD,Male,0,No,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.25,NaN,No
936,5709-LVOEQ,Female,0,Yes,Yes,0,Yes,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Mailed check,80.85,NaN,No
1082,4367-NUYAO,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.75,NaN,No
1340,1371-DWPAZ,Female,0,Yes,Yes,0,No,No phone service,DSL,Yes,...,Yes,Yes,Yes,No,Two year,No,Credit card (automatic),56.05,NaN,No
3331,7644-OMVMY,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,19.85,NaN,No
3826,3213-VVOLG,Male,0,Yes,Yes,0,Yes,Yes,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,25.35,NaN,No
4380,2520-SGTTA,Female,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,Two year,No,Mailed check,20.00,NaN,No
5218,2923-ARZLG,Male,0,Yes,Yes,0,Yes,No,No,No internet service,...,No internet service,No internet service,No internet service,No internet service,One year,Yes,Mailed check,19.70,NaN,No
6670,4075-WKNIU,Female,0,Yes,Yes,0,Yes,Yes,DSL,No,...,Yes,Yes,Yes,No,Two year,No,Mailed check,73.35,NaN,No
6754,2775-SEFEE,Male,0,No,Yes,0,Yes,Yes,DSL,Yes,...,No,Yes,No,No,Two year,Yes,Bank transfer (automatic),61.90,NaN,No

#### since the tenure is not defined, lets drop these columns

In [22]:
df.dropna(inplace = True)
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [23]:
df_range=df.agg([min,max]).T
df_range

                                        min           max
customerID                       0002-ORFBO    9995-HOTOH
gender                               Female          Male
SeniorCitizen                             0             1
Partner                                  No           Yes
Dependents                               No           Yes
tenure                                    1            72
PhoneService                             No           Yes
MultipleLines                            No           Yes
InternetService                         DSL            No
OnlineSecurity                           No           Yes
OnlineBackup                             No           Yes
DeviceProtection                         No           Yes
TechSupport                              No           Yes
StreamingTV                              No           Yes
StreamingMovies                          No           Yes
Contract                     Month-to-month      Two year
PaperlessBilling                         No           Yes
PaymentMethod     Bank transfer (automatic)  Mailed check
MonthlyCharges                        18.25        118.75
TotalCharges                           18.8        8684.8
Churn                                    No           Yes

Since the data looks clean, lets save it in the data folder.

In [24]:
df.to_csv('data/cleaned_data.csv', index=False)